/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/admin/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_api_v1_admin_session_post"];
    /** Logout */
    delete: operations["logout_api_v1_admin_session_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current Admin */
    get: operations["current_admin_api_v1_admin_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/cuisines": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Cuisines */
    get: operations["list_cuisines_api_v1_admin_cuisines_get"];
    put?: never;
    /** Create Cuisine */
    post: operations["create_cuisine_api_v1_admin_cuisines_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/cuisines/{cuisine_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Cuisine */
    delete: operations["delete_cuisine_api_v1_admin_cuisines__cuisine_id__delete"];
    options?: never;
    head?: never;
    /** Update Cuisine */
    patch: operations["update_cuisine_api_v1_admin_cuisines__cuisine_id__patch"];
    trace?: never;
  };
  "/api/v1/admin/restaurants": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Restaurants */
    get: operations["list_restaurants_api_v1_admin_restaurants_get"];
    put?: never;
    /** Create Restaurant Endpoint */
    post: operations["create_restaurant_endpoint_api_v1_admin_restaurants_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/restaurants/{restaurant_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Restaurant */
    get: operations["read_restaurant_api_v1_admin_restaurants__restaurant_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Restaurant */
    patch: operations["patch_restaurant_api_v1_admin_restaurants__restaurant_id__patch"];
    trace?: never;
  };
  "/api/v1/admin/restaurants/{restaurant_id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Publish Restaurant */
    post: operations["publish_restaurant_api_v1_admin_restaurants__restaurant_id__publish_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/restaurants/{restaurant_id}/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archive Restaurant */
    post: operations["archive_restaurant_api_v1_admin_restaurants__restaurant_id__archive_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/geocode": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Geocode Address */
    post: operations["geocode_address_api_v1_admin_geocode_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness */
    get: operations["liveness_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["readiness_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AdminLoginRequest */
    AdminLoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** AdminUserResponse */
    AdminUserResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Role */
      role: string;
    };
    /** CuisineCreate */
    CuisineCreate: {
      /** Slug */
      slug: string;
      /** Display Name */
      display_name: string;
      /** Color */
      color: string;
      /** Icon Key */
      icon_key: string;
    };
    /** CuisineResponse */
    CuisineResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Slug */
      slug: string;
      /** Display Name */
      display_name: string;
      /** Color */
      color: string;
      /** Icon Key */
      icon_key: string;
      /** Is Active */
      is_active: boolean;
    };
    /** CuisineUpdate */
    CuisineUpdate: {
      /** Display Name */
      display_name?: string | null;
      /** Color */
      color?: string | null;
      /** Icon Key */
      icon_key?: string | null;
      /** Is Active */
      is_active?: boolean | null;
    };
    /** GeocodeRequest */
    GeocodeRequest: {
      /** Address */
      address: string;
    };
    /** GeocodeResponse */
    GeocodeResponse: {
      /** Configured */
      configured: boolean;
      /** Candidates */
      candidates: components["schemas"]["GeocodingCandidate"][];
    };
    /** GeocodingCandidate */
    GeocodingCandidate: {
      /** Label */
      label: string;
      /** Latitude */
      latitude: number;
      /** Longitude */
      longitude: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** RestaurantCreate */
    RestaurantCreate: {
      /** Name */
      name: string;
      /** Address */
      address: string;
      /** Menu Url */
      menu_url?: string | null;
      /** Primary Cuisine Id */
      primary_cuisine_id?: string | null;
      /** Price Range */
      price_range?: ("under_200" | "200_to_400" | "400_to_800" | "over_800") | null;
      /** Latitude */
      latitude?: number | null;
      /** Longitude */
      longitude?: number | null;
    };
    /** RestaurantResponse */
    RestaurantResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Address */
      address: string;
      /** Menu Url */
      menu_url: string | null;
      /** Primary Cuisine Id */
      primary_cuisine_id: string | null;
      primary_cuisine: components["schemas"]["CuisineResponse"] | null;
      /** Price Range */
      price_range: ("under_200" | "200_to_400" | "400_to_800" | "over_800") | null;
      /**
       * Status
       * @enum {string}
       */
      status: "draft" | "published" | "archived";
      /**
       * Source Type
       * @constant
       */
      source_type: "manual";
      /** Latitude */
      latitude: number | null;
      /** Longitude */
      longitude: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** RestaurantUpdate */
    RestaurantUpdate: {
      /** Name */
      name?: string | null;
      /** Address */
      address?: string | null;
      /** Menu Url */
      menu_url?: string | null;
      /** Primary Cuisine Id */
      primary_cuisine_id?: string | null;
      /** Price Range */
      price_range?: ("under_200" | "200_to_400" | "400_to_800" | "over_800") | null;
      /** Latitude */
      latitude?: number | null;
      /** Longitude */
      longitude?: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login_api_v1_admin_session_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminLoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_api_v1_admin_session_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  current_admin_api_v1_admin_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_cuisines_api_v1_admin_cuisines_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CuisineResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_cuisine_api_v1_admin_cuisines_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CuisineCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CuisineResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_cuisine_api_v1_admin_cuisines__cuisine_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cuisine_id: string;
      };
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_cuisine_api_v1_admin_cuisines__cuisine_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        cuisine_id: string;
      };
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CuisineUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CuisineResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_restaurants_api_v1_admin_restaurants_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RestaurantResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_restaurant_endpoint_api_v1_admin_restaurants_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RestaurantCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RestaurantResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_restaurant_api_v1_admin_restaurants__restaurant_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurant_id: string;
      };
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RestaurantResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_restaurant_api_v1_admin_restaurants__restaurant_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurant_id: string;
      };
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RestaurantUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RestaurantResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  publish_restaurant_api_v1_admin_restaurants__restaurant_id__publish_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurant_id: string;
      };
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RestaurantResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  archive_restaurant_api_v1_admin_restaurants__restaurant_id__archive_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        restaurant_id: string;
      };
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RestaurantResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  geocode_address_api_v1_admin_geocode_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: {
        bitemap_admin_session?: string | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GeocodeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GeocodeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  liveness_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  readiness_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
}
